### ISSUE TITLE
some problems occurred when reproducing results in this paper

### ISSUE THREAD

**Issue by payphone131** [YapengTian/AV-Robustness-CVPR21#6]
hi, sorry to disturb you but i got some problems when i tried to reproduce your results. my results somtimes would be more than 10% lower than yours so i think there must be something wrong when i run your code. my running procedure on AVE dataset is listed as follows:
(1) run extract_audio.py and extract_frames.py to get audio and frame files.
(2) run train_attack_AVE.sh.
(3) run eval_attack_AVE.sh to see the defense ability of the model obtained by (2). since the epsilons in your defense settings are all 0.006 and in your attack settings are 0.012 sometimes, in order to see and compare the defense ability of the model in the same settings as other defense methods, i changed the epsilons whose values are 0.012 in main_attack.py to 0.006 just like them in main_defense.py.
(4) run train_defense_AVE.sh.
(5) run eval_defense_AVE.sh to see the defense ability of the approach you proposed. according to my understanding i could get the results equal to those in your paper in this step but i didn't.
are there something wrong with my steps?
besides the procedure, i also have other questions:
when i run extract_audio.py and extract_frames.py, i found more than 20 videos in AVE dataset didn't have their audio files. is this normal?
are your results of defense ability of your model on AVE dataset actually under 60 epochs instead of 30? because i have to run (30 + 30) epochs to get your results.
i found the epsilons are 0.06 and 0.12 in your paper and 0.006 and 0.012 in your code, are these typos? i used 0.006 and 0.012 since i thought the parameters in your code are the correct version.

**Comment by YapengTian** [comment]
Thanks for your interest in our work! I think you run the code correctly. Here are some responses to your questions.

(1) In the original implementation, the total epoch number is 100 (as mentioned in the appendix). But, when I was working on the code release, I found that 30 is actually enough to obtain comparable performance on AVE.  For saving training time, I used 30 in the code. But, if you can reproduce similar results with epoch = 60, you can set it as 60.  

(2) All videos in the AVE dataset should be able to extract the corresponding audio files. Any errors you got for the audio extraction?

(3) For the epsilon values, as clarified in the README, "there are typos in the captions of Tab. 1 and Tab. 3. The perturbation strengthens are 0.006 and 0.012 as in Fig. 3 (10^-3) rather than 0.06 and 0.12. "

**Comment by payphone131** [comment]
thanks for your reply! i am going to check my AVE dataset and extraction.

**Comment by payphone131** [comment]
in my AVE dataset there are 4097 videos but i only got 4071 audio files, i am going to check the reason.
